cloud:
  aws:
    credentials:
      access-key: AKIA2HDIMUN7XHVDGAXA
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: gadgetrium-m4


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/gadgetarium
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
    sql:
        init:
            data-locations: classpath:db/data.sql
            mode: always
